// QRQueue/qrqueue.client/src/routes/event/[eventid]/publishing/+page.svelte
﻿<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';

	const eventId = $page.params.eventid;
	let eventName = "";
	let issueCount = 10;
	let totalIssued = 0;

	let isGenerating = false; // 発行中かどうかの状態

	type LogEntry = {
	issuer: string;
	date: string;
	count: number;
	startNumber: number;
	endNumber: number;
	};

	let logs: LogEntry[] = [];

	onMount(async () => {
	let res = await fetch(`/api/event/Name?id=${eventId}`);
	eventName = await res.text();

	// ログ情報をAPIから取得（クエリに eventId を付ける）
	const logRes = await fetch(`/api/pdf/logs?eventDisplayId=${eventId}`);
	if (logRes.ok) {
	const data = await logRes.json();

	logs = data.map(entry => ({
	issuer: entry.issuerName,
	date: new Date(entry.issuedAt).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" }),
	count: entry.count,
	startNumber: entry.startNumber,
	endNumber: entry.endNumber
	}));

	// 合計枚数を再計算
	totalIssued = logs.reduce((sum, log) => sum + log.count, 0);
	} else {
	console.error("ログの取得に失敗しました");
	}
	});

	async function generateTickets() {
	isGenerating = true; // 発行開始
	try {
	const response = await fetch('/api/pdf/generate', {
	method: 'POST',
	headers: {
	'Content-Type': 'application/json'
	},
	body: JSON.stringify({
	count: issueCount,
	eventDisplayId: eventId
	})
	});

	if (!response.ok) {
	alert("PDFの生成に失敗しました");
	return;
	}

	const blob = await response.blob();
	const url = window.URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = 'チケット.pdf';
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);

	// 発行後ログを更新
	await refreshLogs();
	} catch (err) {
	console.error("エラー:", err);
	alert("予期せぬエラーが発生しました");
	} finally {
	isGenerating = false; // 発行終了
	}
	}

	async function refreshLogs() {
	const logRes = await fetch(`/api/pdf/logs?eventDisplayId=${eventId}`);
	if (logRes.ok) {
	const data = await logRes.json();

	logs = data.map(entry => ({
	issuer: entry.issuerName,
	date: new Date(entry.issuedAt).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" }),
	count: entry.count,
	startNumber: entry.startNumber,
	endNumber: entry.endNumber
	}));

	totalIssued = logs.reduce((sum, log) => sum + log.count, 0);
	}
	}
</script>

<style>
	.container {
	padding: 2rem;
	max-width: 800px;
	margin: 0 auto;
	}

	.title {
	font-size: 2rem;
	font-weight: bold;
	margin-bottom: 1.5rem;
	padding-left: 1rem;
	background: linear-gradient(to right, #f0f8ff, transparent);
	}

	.section {
	margin-bottom: 2rem;
	}

	.label {
	font-weight: bold;
	margin-bottom: 0.5rem;
	}

	input[type="number"] {
	padding: 0.5rem;
	font-size: 1rem;
	width: 100px;
	margin-right: 1rem;
	}

	button {
	padding: 0.5rem 1rem;
	font-size: 1rem;
	background-color: #007acc;
	color: white;
	border: none;
	border-radius: 0.4rem;
	cursor: pointer;
	}

	button:disabled {
	background-color: #a0c5e8;
	cursor: not-allowed;
	}

	button:hover:not(:disabled) {
	background-color: #005ea2;
	}

	.log-table {
	width: 100%;
	border-collapse: collapse;
	margin-top: 1rem;
	}

	.log-table th,
	.log-table td {
	border: 1px solid #ccc;
	padding: 0.5rem;
	text-align: center;
	}

	.log-table th {
	background-color: #f0f0f0;
	}
</style>

<div class="container">
	<div class="title">イベント: {eventName}</div>

	<div class="section">
		<div class="label">発行枚数を入力：</div>
		<input type="number" bind:value={issueCount} min="1" />
		<button onclick={generateTickets} disabled={isGenerating}>
			{#if isGenerating}
			発行中...
			{:else}
			チケットを発行
			{/if}
		</button>
	</div>

	<div class="section">
		<div class="label">合計発行枚数: {totalIssued}</div>
		<div class="label">発行ログ:</div>
		<table class="log-table">
			<thead>
				<tr>
					<th>発行者</th>
					<th>発行日時</th>
					<th>枚数</th>
					<th>番号範囲</th>
				</tr>
			</thead>
			<tbody>
				{#each logs as log}
				<tr>
					<td>{log.issuer}</td>
					<td>{log.date}</td>
					<td>{log.count}</td>
					<td>No.{log.startNumber} ～ No.{log.endNumber}</td>
				</tr>
				{/each}
			</tbody>
		</table>
	</div>
</div>

// QRQueue/Views/Event/Publishing.tsx
import { useState, useEffect } from "preact/hooks";
import Layout from "@/Shared/Layout";

type LogEntry = {
    issuer: string;
    date: string;
    count: number;
    startNumber: number;
    endNumber: number;
};

type Model = {
    eventId: string;
};

// SvelteKit routes/event/[eventid]/publishing/+page.svelte から移行
export default function Publishing({ model }: { model: Model }) {
    const [eventName, setEventName] = useState("");
    const [issueCount, setIssueCount] = useState(10);
    const [totalIssued, setTotalIssued] = useState(0);
    const [isGenerating, setIsGenerating] = useState(false);
    const [logs, setLogs] = useState<LogEntry[]>([]);

    useEffect(() => {
        (async () => {
            const res = await fetch(`/api/event/Name?id=${model.eventId}`);
            setEventName(await res.text());

            await refreshLogs();
        })();
    }, [model.eventId]);

    async function loadLogs(): Promise<LogEntry[]> {
        const logRes = await fetch(`/api/pdf/logs?eventDisplayId=${model.eventId}`);
        if (!logRes.ok) {
            console.error("ログの取得に失敗しました");
            return [];
        }
        const data = await logRes.json();
        return data.map((entry: any) => ({
            issuer: entry.issuerName,
            date: new Date(entry.issuedAt).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" }),
            count: entry.count,
            startNumber: entry.startNumber,
            endNumber: entry.endNumber,
        }));
    }

    async function refreshLogs() {
        const loaded = await loadLogs();
        setLogs(loaded);
        setTotalIssued(loaded.reduce((sum, log) => sum + log.count, 0));
    }

    async function generateTickets(e: Event) {
        e.preventDefault();
        setIsGenerating(true);
        try {
            const response = await fetch("/api/pdf/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    count: issueCount,
                    eventDisplayId: model.eventId,
                }),
            });

            if (!response.ok) {
                alert("PDFの生成に失敗しました");
                return;
            }

            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = "チケット.pdf";
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);

            await refreshLogs();
        } catch (err) {
            console.error("エラー:", err);
            alert("予期せぬエラーが発生しました");
        } finally {
            setIsGenerating(false);
        }
    }

    return (
        <Layout>
            <link rel="stylesheet" href="/css/event-publishing.css" />
            <div class="publishing-container">
                <div class="page-title">イベント: {eventName}</div>

                <form class="section issue-form" onSubmit={generateTickets}>
                    <div class="label">発行枚数を入力：</div>
                    <input
                        type="number"
                        min="1"
                        value={issueCount}
                        onInput={(e) => setIssueCount(Number(e.currentTarget.value))}
                    />
                    <button type="submit" class="btn-primary" disabled={isGenerating}>
                        {isGenerating ? "発行中..." : "チケットを発行"}
                    </button>
                </form>

                <div class="section">
                    <div class="label">合計発行枚数: {totalIssued}</div>
                    <div class="label">発行ログ:</div>
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th>発行者</th>
                                <th>発行日時</th>
                                <th>枚数</th>
                                <th>番号範囲</th>
                            </tr>
                        </thead>
                        <tbody>
                            {logs.map((log, i) => (
                                <tr key={i}>
                                    <td>{log.issuer}</td>
                                    <td>{log.date}</td>
                                    <td>{log.count}</td>
                                    <td>No.{log.startNumber} ～ No.{log.endNumber}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </Layout>
    );
}
